repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      -   id: check-case-conflict
      -   id: check-docstring-first
      -   id: check-json
      -   id: check-merge-conflict
      -   id: check-toml
      -   id: check-xml
      -   id: check-yaml
      -   id: debug-statements
      -   id: end-of-file-fixer
      -   id: fix-byte-order-marker  # Forbid UTF-8 byte-order markers
      -   id: mixed-line-ending
      -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black==23.1.0
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    -   id: mypy
        args:
        -   --install-types
        -   --non-interactive
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
